FROM ghcr.io/timmo001/container-debian-base/amd64:stable

SHELL ["/bin/bash", "-o", "pipefail", "-c"]

# Install system
# hadolint ignore=DL3003,DL3018
RUN \
    curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - \
    apt-get update \
    && apt-get install -y --no-install-recommends \
        g++ \
        gcc \
        libavahi-compat-libdnssd-dev \
        libpng++-dev \
        libxext-dev \
        libxss-dev \
        libxtst-dev \
        make	\
        nodejs-current \
        npm \
        python3-dev \
        yarn \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /workspaces

# Set the default shell to bash instead of sh
ENV SHELL /bin/bash
