#!/usr/bin/with-contenv bash
# ==============================================================================
# Starts app
# ==============================================================================
cd /usr/local/share/system-bridge || exit 1

export CLI_ONLY=true
export SB_TRAY=false

exec ./system-bridge
