#!/usr/bin/with-contenv bash
# ==============================================================================
# Starts app
# ==============================================================================
cd /usr/local/share/system-bridge || exit 1

exec ./system-bridge
