---
name: Build Common Steps
description: Common steps for building System Bridge (Go, client, test)

inputs:
  platform:
    description: "Target platform (linux/windows)"
    required: true
  binary_ext:
    description: "Binary extension (e.g., .exe)"
    required: true
  artifact_name:
    description: "Artifact name for output"
    required: true

runs:
  using: "composite"
  steps:
    - name: Set up go
      uses: actions/setup-go@v5
      with:
        cache: true
        go-version-file: "go.mod"

    - uses: oven-sh/setup-bun@v2

    - name: Cache go build
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-build-${{ hashFiles('**/go.mod', '**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-build-

    - name: Cache bun
      uses: actions/cache@v4
      with:
        path: |
          ~/.bun/install/cache
        key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lock') }}
        restore-keys: |
          ${{ runner.os }}-bun-cache-

    - name: Install dependencies
      run: |
        go mod download
        go mod verify
      shell: bash

    - name: Cache Next.js build cache
      uses: actions/cache@v4
      with:
        path: ${{ github.workspace }}/.next/cache
        key: ${{ runner.os }}-nextjs-${{ hashFiles('**/bun.lock') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
        restore-keys: |
          ${{ runner.os }}-nextjs-${{ hashFiles('**/bun.lock') }}

    - name: Build client project
      run: make build_client
      shell: bash

    - name: Run tests
      run: go test -v ./...
      shell: bash
