name: "Bug report"
description: "Create a report to help improve System Bridge"
labels: ["bug"]
assignees: []
body:
  - type: checkboxes
    id: prerequisites
    attributes:
      label: "Prerequisites"
      description: "Please confirm the following before submitting."
      options:
        - label: "I am using the latest release of System Bridge."
          required: true
        - label: "I have read the README and relevant documentation."
          required: false
  - type: input
    id: version
    attributes:
      label: "System Bridge version"
      description: "Version you have installed. Can also be found via the system module."
      placeholder: "e.g., 5.0.1"
    validations:
      required: true
  - type: dropdown
    id: install-method
    attributes:
      label: "Installation method"
      options:
        - "Windows installer"
        - "Arch Linux package (make install_arch)"
        - "Debian/Ubuntu package (.deb)"
        - "Flatpak"
        - "Built from source (make build)"
        - "Other (Please specify)"
    validations:
      required: true
  - type: input
    id: install-method-details
    attributes:
      label: "Installation method details"
      description: "Please specify if you are using a custom installation method."
      placeholder: "e.g., Docker/Container"
    validations:
      required: false
  - type: dropdown
    id: os
    attributes:
      label: "Operating system"
      options:
        - "Linux"
        - "Windows"
        - "Mac OS"
    validations:
      required: true
  - type: input
    id: os-details
    attributes:
      label: "OS details"
      description: "Distro and version (Linux), Windows build, or macOS version."
      placeholder: "e.g., Arch Linux (kernel 6.x) | Windows 11 24H2 | macOS 14.x"
    validations:
      required: false
  - type: textarea
    id: description
    attributes:
      label: "Describe the bug"
      description: "A clear and concise description of what the bug is."
      placeholder: "What happened? What did you expect to happen?"
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: "Steps to reproduce"
      description: "Provide minimal, exact steps to reproduce the issue."
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Observe '...'
    validations:
      required: false
  - type: textarea
    id: expected
    attributes:
      label: "Expected behavior"
      placeholder: "What did you expect to happen?"
    validations:
      required: false
  - type: textarea
    id: actual
    attributes:
      label: "Actual behavior"
      placeholder: "What actually happened? Include any error messages."
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: "Relevant logs/output"
      description: "Paste logs or console output. Redact sensitive info. Can be accessed via the tray icon and opening the logs directory."
      render: bash
      placeholder: |
        # On Linux/macOS (if run from terminal)
        $ system-bridge --version
        $ journalctl -u system-bridge -b --no-pager  # if applicable

        # On Windows (PowerShell)
        PS> system-bridge --version
    validations:
      required: false
  - type: textarea
    id: extra
    attributes:
      label: "Additional context / screenshots"
      description: "Add any other context about the problem here. Drag-and-drop images to attach."
    validations:
      required: false
