---
name: "Sync labels"

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - master
    paths:
      - .github/labels.yml
  schedule:
    - cron: "34 5 * * *"
  workflow_dispatch:

jobs:
  labels:
    # yamllint disable-line rule:line-length
    uses: timmo001/workflows/.github/workflows/labels.yml@2fb2fa1ffdd2f4808768bf86828482660e366a13 # 20261008.3
    with:
      labels-ref: 635f5727c8686b952f53d2fbe1d2e80d2480c831
