---
name: Setup Go Steps
description: Common steps for setting up System Bridge (Go)

runs:
  using: "composite"
  steps:
    - uses: ./.github/actions/setup-runtime

    - name: Clean go module cache
      run: |
        rm -rf ~/go/pkg/mod
      shell: bash

    - name: Cache go build
      uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-build-${{ hashFiles('mise.toml', '**/go.mod', '**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-build-

    - name: Install dependencies
      run: |
        mise exec -- go mod download
        mise exec -- go mod verify
      shell: bash
