# generated by datamodel-codegen:
#   filename:  api_response.json

from __future__ import annotations

from pydantic import BaseModel, Extra, Field


class ApiResponse(BaseModel):
    """
    API Response
    """

    class Config:
        extra = Extra.allow

    message: str = Field(..., description='Message')
