# generated by datamodel-codegen:
#   filename:  battery.json
#   timestamp: 2022-05-13T15:01:54+00:00

from __future__ import annotations

from pydantic import BaseModel, Extra


class LastUpdated(BaseModel):
    class Config:
        extra = Extra.allow

    is_charging: float
    percentage: float


class Model(BaseModel):
    class Config:
        extra = Extra.allow

    is_charging: bool
    percentage: float
    last_updated: LastUpdated
