# generated by datamodel-codegen:
#   filename:  battery.json

from __future__ import annotations

from pydantic import BaseModel, Extra, Field


class LastUpdated(BaseModel):
    """
    Last updated
    """

    class Config:
        extra = Extra.allow

    is_charging: float
    percentage: float


class Battery(BaseModel):
    """
    Battery
    """

    class Config:
        extra = Extra.allow

    is_charging: bool
    percentage: float
    last_updated: LastUpdated = Field(..., description='Last updated')
