# generated by datamodel-codegen:
#   filename:  battery.json
#   timestamp: 2022-05-13T14:56:02+00:00

from __future__ import annotations

from pydantic import BaseModel


class LastUpdated(BaseModel):
    is_charging: float
    percentage: float


class Model(BaseModel):
    is_charging: bool
    percentage: float
    last_updated: LastUpdated
