# generated by datamodel-codegen:
#   filename:  bridge.json
#   timestamp: 2022-05-13T14:56:03+00:00

from __future__ import annotations

from typing import Dict

from pydantic import BaseModel, Extra


class Model(BaseModel):
    class Config:
        extra = Extra.allow

    last_updated: Dict[str, float]
