# generated by datamodel-codegen:
#   filename:  disk.json
#   timestamp: 2022-05-13T15:01:55+00:00

from __future__ import annotations

from pydantic import BaseModel, Extra


class LastUpdated(BaseModel):
    class Config:
        extra = Extra.allow

    io_counters_read_count: float
    io_counters_write_count: float
    io_counters_read_bytes: float
    io_counters_write_bytes: float
    io_counters_read_time: float
    io_counters_write_time: float


class Model(BaseModel):
    class Config:
        extra = Extra.allow

    io_counters_read_count: int
    io_counters_write_count: int
    io_counters_read_bytes: int
    io_counters_write_bytes: int
    io_counters_read_time: int
    io_counters_write_time: int
    last_updated: LastUpdated
