# generated by datamodel-codegen:
#   filename:  gpu.json

from __future__ import annotations

from pydantic import BaseModel, Extra, Field


class Gpu(BaseModel):
    """
    GPU
    """

    class Config:
        extra = Extra.allow

    last_updated: dict[str, float] = Field(..., description='Last updated')
