# generated by datamodel-codegen:
#   filename:  keyboard.json

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel


class Keyboard(BaseModel):
    """
    Keyboard
    """

    key: Optional[str] = None
    text: Optional[str] = None
