# generated by datamodel-codegen:
#   filename:  media_play.json

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel


class MediaPlay(BaseModel):
    """
    Media Play
    """

    autoplay: Optional[bool] = False
    url: str
    volume: Optional[float] = 40
