# generated by datamodel-codegen:
#   filename:  media_write_file.json

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel


class MediaWriteFile(BaseModel):
    """
    Write File
    """

    base: str
    path: Optional[str] = None
    filename: str
