# generated by datamodel-codegen:
#   filename:  media_get_file.json

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel


class MediaGetFile(BaseModel):
    """
    Get File
    """

    base: str
    path: Optional[str] = None
