# generated by datamodel-codegen:
#   filename:  media_play.json

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel


class MediaPlay(BaseModel):
    """
    Media Play
    """

    type: Optional[str] = None
    base: Optional[str] = None
    path: Optional[str] = None
    album: Optional[str] = None
    artist: Optional[str] = None
    autoplay: Optional[bool] = False
    cover: Optional[str] = None
    title: Optional[str] = None
    url: Optional[str] = None
    volume: Optional[float] = 40
