# generated by datamodel-codegen:
#   filename:  media.json

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel


class Media(BaseModel):
    """
    Media Info
    """

    title: Optional[str] = None
    subtitle: Optional[str] = None
    album_artist: Optional[str] = None
    album_title: Optional[str] = None
    artist: Optional[str] = None
    thumbnail: Optional[str] = None
    track_number: Optional[int] = None
