---
name: Setup Client (Web)
description: Setup steps for the System Bridge web client

runs:
  using: "composite"
  steps:
    - uses: pnpm/action-setup@v4
      with:
        package_json_file: web-client/package.json

    - name: Cache pnpm
      uses: actions/cache@v4
      with:
        path: |
          ~/.pnpm-store
        key: ${{ runner.os }}-pnpm-v1-${{ hashFiles('web-client/**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-v1-
