---
name: Setup Client (Web)
description: Setup steps for the System Bridge web client

runs:
  using: "composite"
  steps:
    - uses: pnpm/action-setup@v4
      with:
        package_json_file: web-client/package.json

    - uses: actions/setup-node@v6
      with:
        node-version-file: .node-version
        cache: pnpm
        cache-dependency-path: web-client/pnpm-lock.yaml
