---
name: "Dependency Review"

# yamllint disable-line rule:truthy
on:
  - pull_request

permissions:
  contents: read

jobs:
  dependency-review:
    uses: timmo001/workflows/.github/workflows/depedency-review.yml@master
