---
name: "Sync labels"

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - master
    paths:
      - .github/labels.yml
  schedule:
    - cron: "34 5 * * *"
  workflow_dispatch:

jobs:
  labels:
    uses: timmo001/workflows/.github/workflows/labels.yml@master
