#!/bin/bash
# ==============================================================================
# Initialise backend
# ==============================================================================
python3 -m systembridgebackend --cli --no-gui --init

SB_TOKEN="$(python3 -m systembridgecli token)"
echo "--------------------------------------------------"
echo "Your token is: $SB_TOKEN"
echo "--------------------------------------------------"

# ==============================================================================
# Start app
# ==============================================================================
export XDG_CONFIG_HOME="/data/user/config"
export XDG_DATA_HOME="/data/user/local/share"

python3 -m systembridgebackend --cli --no-gui
