# generated by datamodel-codegen:
#   filename:  media_control.json

from __future__ import annotations

from enum import Enum
from typing import Any, Optional

from pydantic import BaseModel


class Action(Enum):
    play = "play"
    pause = "pause"
    stop = "stop"
    previous = "previous"
    next = "next"
    seek = "seek"
    rewind = "rewind"
    fastforward = "fastforward"
    shuffle = "shuffle"
    repeat = "repeat"
    mute = "mute"
    volume = "volume"


class MediaControl(BaseModel):
    """
    Media Control
    """

    action: Action
    value: Optional[Any] = None
