# generated by datamodel-codegen:
#   filename:  open.json

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel


class Open(BaseModel):
    """
    Keyboard
    """

    path: Optional[str] = None
    url: Optional[str] = None
