# generated by datamodel-codegen:
#   filename:  request.json

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Field


class Request(BaseModel):
    """
    Request
    """

    api_key: Optional[str] = Field(None, description="API Key")
    id: Optional[str] = Field(None, description="Message ID")
    event: str = Field(..., description="Event")
