# generated by datamodel-codegen:
#   filename:  response.json

from __future__ import annotations

from pydantic import BaseModel, Extra, Field


class Response(BaseModel):
    """
    Response
    """

    class Config:
        extra = Extra.allow

    message: str = Field(..., description="Message")
