# generated by datamodel-codegen:
#   filename:  sensors.json

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Field


class Sensors(BaseModel):
    """
    Sensors
    """

    id: Optional[str] = Field(None, description="Event ID")
    last_updated: Optional[dict[str, float]] = Field(None, description="Last updated")
