# generated by datamodel-codegen:
#   filename:  system.json
#   timestamp: 2022-05-13T14:56:06+00:00

from __future__ import annotations

from pydantic import BaseModel


class LastUpdated(BaseModel):
    boot_time: float
    fqdn: float
    hostname: float
    ip_address_4: float
    mac_address: float
    platform: float
    platform_version: float
    uptime: float
    uuid: float
    version: float
    version_latest: float
    version_newer_avaliable: float


class Model(BaseModel):
    boot_time: float
    fqdn: str
    hostname: str
    ip_address_4: str
    mac_address: str
    platform: str
    platform_version: str
    uptime: float
    uuid: str
    version: str
    version_latest: str
    version_newer_avaliable: bool
    last_updated: LastUpdated
