---
name: Build Client (Web)
description: Build steps for the System Bridge web client

runs:
  using: "composite"
  steps:
    - uses: ./.github/actions/setup-client-web

    - name: Cache Next.js build cache
      uses: actions/cache@v4
      with:
        path: ${{ github.workspace }}/web-client/.next/cache
        key: ${{ runner.os }}-nextjs-${{ hashFiles('**/bun.lock') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
        restore-keys: |
          ${{ runner.os }}-nextjs-${{ hashFiles('**/bun.lock') }}

    - name: Build client project
      run: make build_client
      shell: bash
