---
name: Build Client (Web)
description: Build steps for the System Bridge web client

runs:
  using: "composite"
  steps:
    - uses: ./.github/actions/setup-client-web

    - name: Cache Next.js build cache
      uses: actions/cache@v4
      with:
        path: ${{ github.workspace }}/web-client/.next/cache
        key: ${{ runner.os }}-nextjs-v2-${{ hashFiles('web-client/**/bun.lock') }}-${{ hashFiles('web-client/**/*.js', 'web-client/**/*.jsx', 'web-client/**/*.ts', 'web-client/**/*.tsx') }}
        restore-keys: |
          ${{ runner.os }}-nextjs-v2-${{ hashFiles('web-client/**/bun.lock') }}

    - name: Build client project
      run: make build_web_client
      shell: bash
