---
name: "Build"

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    # master
    # yamllint disable-line rule:line-length
    uses: timmo001/workflows/.github/workflows/build-python-linux.yml@0f94251168336b74fadf271a955d24d1de4de343 # 20260927.1
