---
name: "Build"

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    # master
    # yamllint disable-line rule:line-length
    uses: timmo001/workflows/.github/workflows/build-python-linux.yml@4562274d170ccaa4b5d5bc776684caaa8d61b007 # 20261002.0
