---
name: Build and push CI Docker images

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - master
    paths:
      - .github/workflows/build-and-push-ci-image.yml
      - Dockerfile.ci-build-arch
  schedule:
    - cron: "0 3 * * 0" # Every Sunday at 03:00 UTC
  workflow_dispatch:

jobs:
  build-and-push:
    name: Build and push CI ${{ matrix.os }} image
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os:
          - arch
          - ubuntu
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.ci-build-${{ matrix.os }}
          push: true
          tags: ghcr.io/${{ github.repository }}/ci-build-${{ matrix.os }}:latest
