---
name: "Dependency Review"

# yamllint disable-line rule:truthy
on:
  - pull_request

permissions:
  contents: read

jobs:
  dependency-review:
    # master
    # yamllint disable-line rule:line-length
    uses: timmo001/workflows/.github/workflows/dependency-review.yml@82ee28374d3471231113dabc3dd436f65a47132f # 20261004.0
