---
name: "Dependency Review"

# yamllint disable-line rule:truthy
on:
  - pull_request

permissions:
  contents: read

jobs:
  dependency-review:
    # master
    # yamllint disable-line rule:line-length
    uses: timmo001/workflows/.github/workflows/dependency-review.yml@36527a2230bed48409ccd595b17f8344efe0acdd # 20261001.1
