---
name: "Dependency Review"

# yamllint disable-line rule:truthy
on:
  - pull_request

permissions:
  contents: read

jobs:
  dependency-review:
    # master
    # yamllint disable-line rule:line-length
    uses: timmo001/workflows/.github/workflows/dependency-review.yml@da1f8d52a56ce02034b676a8c91275e822934a68 # 20261001.0
