name: Deploy Linux

# yamllint disable-line rule:truthy
on:
  release:
    types:
      - published
  workflow_run:
    workflows:
      - "Build Linux"
    branches:
      - master
    types:
      - completed
  workflow_dispatch:

jobs:
  deploy-linux:
    uses: timmo001/workflows/.github/workflows/deploy-node-executable-linux.yml@master
    secrets:
      CONTAINER_SLUG: system-bridge
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
