---
name: "Sync labels"

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - master
    paths:
      - .github/labels.yml
  schedule:
    - cron: "34 5 * * *"
  workflow_dispatch:

jobs:
  labels:
    # yamllint disable-line rule:line-length
    uses: timmo001/workflows/.github/workflows/labels.yml@f8d0daf26e163f0ee997d759fbf0f7daeb598c43 # 20261008.2
    with:
      labels-ref: 635f5727c8686b952f53d2fbe1d2e80d2480c831
