---
name: "Sync labels"

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - master
    paths:
      - .github/labels.yml
  schedule:
    - cron: "34 5 * * *"
  workflow_dispatch:

jobs:
  labels:
    # master
    # yamllint disable-line rule:line-length
    uses: timmo001/workflows/.github/workflows/labels.yml@4562274d170ccaa4b5d5bc776684caaa8d61b007 # 20261002.0
    with:
      labels-ref: 635f5727c8686b952f53d2fbe1d2e80d2480c831
