---
name: "Sync labels"

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - master
    paths:
      - .github/labels.yml
  schedule:
    - cron: "34 5 * * *"
  workflow_dispatch:

jobs:
  labels:
    # master
    # yamllint disable-line rule:line-length
    uses: timmo001/workflows/.github/workflows/labels.yml@a76c7b0547b8e4c16fdbbdb9d2ba3cbab144b168 # 20261002.1
    with:
      labels-ref: 635f5727c8686b952f53d2fbe1d2e80d2480c831
