---
name: Label Legacy

on:
  issues:
    types: [labeled]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.issue.number }}
  cancel-in-progress: true

jobs:
  comment:
    runs-on: ubuntu-latest
    if: github.event.label.name == 'legacy'
    steps:
      - name: Add comment
        uses: actions/github-script@v7
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const issue_number = context.issue.number;
            const comment = `
            This issue has been marked as "legacy" because it pertains to a version of the application that is being replaced.

            For more information on the application rebuild, please see the main tracking issue: #3392 and the project [README](README.md).

            Once the new version is released, this issue will be re-evaluated. Thank you for your patience.
            `;
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issue_number,
              body: comment
            });
