---
name: Lint general

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - dev
  pull_request:
    types:
      - opened
      - synchronize
  workflow_dispatch: {}

jobs:
  lint:
    uses: timmo001/workflows/.github/workflows/lint-general.yml@a579ffd827f9944e936ae691ac0b82aa5155963e # master
