---
name: Lint general

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - dev
  pull_request:
    types:
      - opened
      - synchronize
  workflow_dispatch: {}

permissions: {}

jobs:
  lint:
    uses: timmo001/workflows/.github/workflows/lint-general.yml@f72d1eb6c310502499f5551d65ceca1e478eb266 # 20261003.0
