---
name: Lint general

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - dev
  pull_request:
    types:
      - opened
      - synchronize
  workflow_dispatch: {}

jobs:
  lint:
    uses: timmo001/workflows/.github/workflows/lint-general.yml@5ac04fe2224a08a24ed276dca438dc68360e1e2d # master
