---
name: "Release Drafter"

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  release-drafter:
    # master
    # yamllint disable-line rule:line-length
    uses: timmo001/workflows/.github/workflows/release-drafter.yml@82ee28374d3471231113dabc3dd436f65a47132f # 20261004.0
