---
name: "Release Drafter"

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  release-drafter:
    # master
    # yamllint disable-line rule:line-length
    uses: timmo001/workflows/.github/workflows/release-drafter.yml@a76c7b0547b8e4c16fdbbdb9d2ba3cbab144b168 # 20261002.1
