---
name: "Release Drafter"

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  release-drafter:
    # master
    # yamllint disable-line rule:line-length
    uses: timmo001/workflows/.github/workflows/release-drafter.yml@da1f8d52a56ce02034b676a8c91275e822934a68 # 20261001.0
