---
name: Renovate automerge

# yamllint disable-line rule:truthy
on:
  pull_request_target: {}

jobs:
  automerge:
    uses: timmo001/workflows/.github/workflows/renovate-automerge.yml@7f8dd7688477dbdd147aa0e9ec381a4c72e63a0e # master
    permissions:
      pull-requests: write
      contents: write
