---
name: Renovate automerge

# yamllint disable-line rule:truthy
on:
  pull_request_target: {}

jobs:
  automerge:
    uses: timmo001/workflows/.github/workflows/renovate-automerge.yml@ee51b59fac85756d78f89c26f2c5db58ecd5d36a # master
    permissions:
      pull-requests: write
      contents: write
