---
name: Renovate automerge

# yamllint disable-line rule:truthy
on:
  pull_request_target: {}

jobs:
  automerge:
    uses: timmo001/workflows/.github/workflows/renovate-automerge.yml@4797d9f93b2636e75dda38232aac206ac161f7e5 # master
    permissions:
      pull-requests: write
      contents: write
