---
name: "Test"

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    # master
    # yamllint disable-line rule:line-length
    uses: timmo001/workflows/.github/workflows/test-pytest.yml@82ee28374d3471231113dabc3dd436f65a47132f # 20261004.0
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    with:
      module-name: "systembridgeconnector"
