---
name: "Test"

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    # yamllint disable-line rule:line-length
    uses: timmo001/workflows/.github/workflows/test-pytest.yml@fcc6d0528cf0533614d1162c5c5b8ebbb6dfdad5 # 20261008.1
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    with:
      # renovate: datasource=custom.home-assistant-python-minor depName=python
      python-version: "3.14"
      module-name: "systembridgeconnector"
